services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  
  server:
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: "./server/.env"
    develop:
      watch:
        - action: sync+restart
          path: "./server"
          target: /app
    depends_on:
      - redis
  
  client:
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - 80:80
    develop:
      watch:
        - action: sync+restart
          path: "./client"
          target: /app
    depends_on:
      - server

volumes:
  redis_data: