version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    env_file:
      - "./server/.env"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass $${REDIS_PASSWORD}
  
  server:
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - "./server/.env"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
  
  client:
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - server

volumes:
  redis_data: